import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@prueba/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"flex flex-col justify-between items-center p-24 min-h-screen"}>
        <div className={"flex justify-between items-center text-sm max-w-6xl w-full z-2 font-mono"}>
          <p
              className={"m-0 p-4 relative bg-coolGray-100/50 rounded-xl border border-white/30"}
          >
            Get started by editing&nbsp;
            <code className={"font-bold font-mono"}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={"flex justify-center items-center gap-2"}
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={"invert"}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={"relative flex justify-center items-center py-24"}>
          <Image
            className={"z-20 relative invert"}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
  <div className="absolute w-60 h-60 z-0 ml-44 blur-3xl rotate-45 bg-gradient-to-tl from-transparent via-blue-900 to-transparent"></div>
        </div>

        <div className={"grid grid-cols-4 w-screen max-w-full"}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={"group px-4 py-5 border border-white/0 bg-gray-500/0 rounded-xl transition-all ease-in-out hover:border-white/20 hover:bg-gray-500/10 duration-200"}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className="font-semibold	mb-3 ">
              Docs <span
              className="inline-block group-hover:translate-x-1 transition-transform"
              >-&gt;</span>
            </h2>
            <p className="m-0 opacity-60 text-sm">
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={"group px-4 py-5 border border-white/0 bg-gray-500/0 rounded-xl transition-all ease-in-out hover:border-white/20 hover:bg-gray-500/10 duration-200"}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className="font-semibold	mb-3">
              Learn <span
              className="inline-block group-hover:translate-x-1 transition-transform"
              >-&gt;</span>
            </h2>
            <p className="m-0 opacity-60 text-sm">
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={"px-4 py-5 border border-white/0 bg-gray-500/0 rounded-xl transition-all ease-in-out hover:border-white/20 hover:bg-gray-500/10 duration-200 group "}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className="font-semibold	mb-3">
              Templates <span
              className="inline-block group-hover:translate-x-1 transition-transform"
              >-&gt;</span>
            </h2>
            <p className="m-0 opacity-60 text-sm">
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={"group px-4 py-5 border border-white/0 bg-gray-500/0 rounded-xl transition-all ease-in-out hover:border-white/20 hover:bg-gray-500/10 duration-200"}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className="font-semibold	mb-3">
              Deploy <span
              className="inline-block group-hover:translate-x-1 transition-transform"
              >-&gt;</span>
            </h2>
            <p className="m-0 opacity-60 text-sm">
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
